;;; my-packages-autoloads.el --- automatically extracted autoloads (do not edit)   -*- lexical-binding: t -*-
;; Generated by the `loaddefs-generate' function.

;; This file is part of GNU Emacs.

;;; Code:

(add-to-list 'load-path (or (and load-file-name (directory-file-name (file-name-directory load-file-name))) (car load-path)))



;;; Generated autoloads from my-copilot-chat-git.el

(autoload 'my-copilot-chat-generate-commit-message "my-copilot-chat-git" "\
Auto insert commit message from staged diff via Copilot Chat." t)
(autoload 'my-copilot-chat--git-commit-setup "my-copilot-chat-git" "\
Generate commit message shortly after commit buffer opens.")
(register-definition-prefixes "my-copilot-chat-git" '("my-copilot-chat-"))


;;; Generated autoloads from my-git.el

(autoload 'my-projectile-run-shell-command-in-root "my-git" "\
Invoke `shell-command' COMMAND in the project's root.

(fn COMMAND)")
(autoload 'my-gh-repo-view "my-git" "\
Gh repo view." t)
(autoload 'my-gh-co "my-git" "\
Gh checkout TARGET.

(fn TARGET)" t)
(autoload 'my-gh-pr-view "my-git" "\
Gh open pr." t)
(autoload 'my-gh-pr-create "my-git" "\
Gh pr create." t)
(autoload 'my-gh-pr-list "my-git" "\
Gh pull request list." t)
(autoload 'my-git-open-pr-from-commit-hash "my-git" "\
Git openpr HASH.

(fn HASH)" t)
(autoload 'my-git-open-pr-from-current-line "my-git" "\
Git openpr current line." t)
(autoload 'my-consult-git-commit-messages "my-git" nil t)
(autoload 'my-consult-git-conventional-commit-prefix "my-git" nil t)
(autoload 'my-git-wip "my-git" nil t)
(autoload 'my-git-unwip "my-git" nil t)


;;; Generated autoloads from my-js.el

(autoload 'my-deno-project-p "my-js" "\
Predicate for determining if the open project is a Deno one.")
(autoload 'my-node-project-p "my-js" "\
Predicate for determining if the open project is a Node one.")
(autoload 'my-copy-project-name-clipboard "my-js" "\
Copy project name to clipbord." t)
(autoload 'my-reload-dir-locals-for-current-buffer "my-js" "\
reload dir locals for the current buffer" t)
(autoload 'my-vitest-copy-command-current-buffer "my-js" "\
Run vitest for current file and copy command to clipboard." t)
(autoload 'my-vitest-copy-command-watch-current-buffer "my-js" "\
Watch vitest for current file and copy command to clipboard." t)
(autoload 'my-vitest-command-watch-tmux "my-js" "\
Watch vitest for current file in another tmux pane." t)
(autoload 'my-tsc-error-find-file-buffer "my-js" "\
Show tsc error on buffer.
Optional argument TSC-COMMAND is the TypeScript check command to use.
If not provided, it will detect and use the appropriate command based on the project.

(fn &optional TSC-COMMAND)" t)
(autoload 'my-eslint-error-find-file-buffer "my-js" "\
Show sorted eslint warning on buffer.
Optional argument ESLINT-COMMAND is the eslint command to use.
If not provided, it will detect and use the appropriate command based on the project.

(fn &optional ESLINT-COMMAND)" t)
(autoload 'my-eslint-spefic-error-find-file-buffer "my-js" "\
Show eslint ERROR-NAME error on buffer.
Optional argument ESLINT-COMMAND is the eslint command to use.

(fn ERROR-NAME &optional ESLINT-COMMAND)" t)
(autoload 'my-eslint-fix-file "my-js" "\
Run eslint for current file." t)
(register-definition-prefixes "my-js" '("my-"))


;;; Generated autoloads from my-util.el

(autoload 'my-generate-autoloads "my-util" "\
Generates autoloads." t)
(autoload 'my-set-alpha "my-util" "\
Set frame parameter ALPHA-NUM.

(fn ALPHA-NUM)" t)
(autoload 'my-buffer-face-set-variable-pitch-font "my-util" "\
Change the current buffer font to variable pitch font." t)
(autoload 'my-fullscreen "my-util" "\
Set frame maxmize." t)
(autoload 'my-halfscreen "my-util" "\
Set frame half." t)
(autoload 'my-halfscreen-right "my-util" "\
Set frame half." t)
(autoload 'my-url-decode-region "my-util" "\
BEGからENDの範囲の文字をURLデコードする.

(fn BEG END)" t)
(autoload 'my-url-encode-region "my-util" "\
BEGからENDの範囲の文字をURLエンコードする.

(fn BEG END)" t)
(autoload 'unicode-unescape-region "my-util" "\
指定した範囲のUnicodeエスケープ文字(\\uXXXX)をデコードする.

(fn START END)" t)
(autoload 'unicode-escape-region "my-util" "\
指定した範囲の文字をUnicodeエスケープする.

(fn &optional START END)" t)
(autoload 'my-reverse-chars-region "my-util" "\
BEGからENDの範囲の文字反転する.

(fn BEG END)" t)
(autoload 'my-uniq-lines "my-util" "\
Unique lines in region.
Called from a program, there are two arguments:
BEG and END (region to sort).

(fn BEG END)" t)
(autoload 'my-reopen-with-sudo-tramp "my-util" "\
Reopen current buffer-file with sudo using tramp." t)
(autoload 'my-copy-buffer-name-clipboard "my-util" "\
Copy buffer name to clipbord." t)
(autoload 'my-copy-file-path-with-location "my-util" "\
Copy current file path with point/region location to clipboard.

When region is active, copy start and end as
`/path/to/file:LINE:COLUMN-ENDLINE:ENDCOLUMN'.
Otherwise copy point as `/path/to/file:LINE:COLUMN'." t)
(autoload 'my-move-or-rename-this-file "my-util" "\
Move or Rename current buffer file to NEWFILE.

(fn NEWFILE)" t)
(autoload 'my-copy-this-file "my-util" "\
Copy current buffer file to new file." t)
(autoload 'my-delete-or-remove-this-file "my-util" "\
Delete current buffer file." t)
(autoload 'my-find-file-and-create-directory "my-util" "\
Find a file, and then create FILENAME (WILDCARDS)
the folder if it doesn't exist.

(fn FILENAME &optional WILDCARDS)" t)
(autoload 'my-generate-slack-reminder "my-util" "\
Generate slack reminder with CONTENT and copy to clipboard.

(fn CONTENT)" t)
(autoload 'my-open-hyper-current-buffer "my-util" "\
Open current buffer with Hyper term and fish." t)
(autoload 'my-open-alacritty-tmux-current-buffer "my-util" "\
Open current buffer with tmux." t)
(autoload 'my-open-scratch "my-util" "\
Open *scratch* buffer ." t)
(autoload 'open-today-org-file "my-util" "\
Open a today org file." t)
(autoload 'my-open "my-util" "\
Open finder." t)
(autoload 'my-other-window-or-split "my-util" "\
Switch to other window or split window." t)
(autoload 'my-other-window-or-split-and-kill-minibuffer "my-util" "\
Switch to other window or split window and kill minibuffer." t)
(autoload 'my-create-ics-file-from-text "my-util" "\
テキストからICSファイルを作成し、デスクトップに保存します。

(fn TEXT)" t)
(autoload 'my-show-unixtime-at-point-or-region "my-util" "\
ポイントまたはリージョンのUNIXTIMEを日本語形式で表示する。" t)
(autoload 'my-insert-unixtime "my-util" "\
指定した時間または現在時刻をUNIXTIMEとして挿入する。
TIME-STRが与えられた場合は、ISO8601形式の時間文字列をUNIXTIMEに変換する。
例: 2020-01-15T16:12:21Z, 2023-12-25T10:30:00+09:00
指定がない場合は現在時刻のUNIXTIMEを挿入する。

(fn &optional TIME-STR)" t)
(autoload 'my/clear-side-window-lock "my-util" "\
side window 起因で split できない状態を解除する。" t)
(register-definition-prefixes "my-util" '("char-unicode" "minibuffer-keyboard-quit" "my-" "open-today-org-file-format" "unicode-char" "url-"))


;;; End of scraped data

(provide 'my-packages-autoloads)

;; Local Variables:
;; version-control: never
;; no-byte-compile: t
;; no-update-autoloads: t
;; no-native-compile: t
;; coding: utf-8-emacs-unix
;; End:

;;; my-packages-autoloads.el ends here
