(source gnu)
(source marmalade)
(source melpa)


(depends-on "auctex")
(depends-on "auctex-latexmk")
(depends-on "auto-complete-auctex")

(depends-on "magit")
(depends-on "git-commit-mode")
(depends-on "git-rebase-mode")
(depends-on "gitconfig-mode")
(depends-on "gitignore-mode")
(depends-on "git-gutter")
(depends-on "projectile")

(depends-on "py-autopep8")
(depends-on "python-environment")
(depends-on "epc")
(depends-on "jedi")

(depends-on "markdown-mode")

(depends-on "helm")
(depends-on "helm-descbinds")
(depends-on "helm-migemo")
(depends-on "helm-pydoc")
(depends-on "helm-projectile")

(depends-on "anzu")
(depends-on "auto-complete")
(depends-on "exec-path-from-shell")
(depends-on "expand-region")
(depends-on "flycheck")
(depends-on "google-translate")
(depends-on "init-loader")
(depends-on "key-chord")
(depends-on "key-combo")
(depends-on "migemo")
(depends-on "multiple-cursors")
(depends-on "popup")
(depends-on "popwin")
(depends-on "powerline")
(depends-on "quickrun")
(depends-on "recentf-ext")
(depends-on "smartrep")
(depends-on "undo-tree")
(depends-on "yasnippet")

(depends-on "monokai-theme")

(depends-on "concurrent")
(depends-on "ctable")
(depends-on "dash")
(depends-on "deferred")
(depends-on "epl")
(depends-on "s")
(depends-on "f")
(depends-on "pkg-info")
